name: chat_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

# Dart SDK version constraints
environment:
  sdk: '>=3.0.6 <4.0.0'

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  url_launcher: ^6.2.5


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/


  # If you want to add fonts, you can use this structure:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
